### PR TITLE
bump ruby version + fix install (Patch Gemfile to fix blurhash and ox packages)

### LINKED ISSUE #82: rbenv: version 3.0.4 is not installed
Update to 2022.10.21~ynh1 works perfectly fine -- no errors.

Running admin `tootctl` commands produces
`rbenv: version '3.0.4' is not installed (set by /var/www/glitchsoc/live/.ruby-version)`

Going through the update log, installer does indeed install 3.0.3, not 3.0.4 that is required.

### Context
Hardware: VPS
Yunohost version: 4.4.2.14
Glitch-soc version: 2022.08.01~ynh1 update through CLI

### PR DESCRIPTION
**Pull request by lapineige**
Fix #82 #97

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by yalh76** [comment]
https://ci-apps-dev.yunohost.org/ci/job/5068

**Comment by lapineige** [comment]
And I added the install fix from Mastodon app: https://github.com/YunoHost-Apps/mastodon_ynh/pull/360

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
@Tagadda if CI is happy (as expected…) please merge it soon, install is currently broken :(

**Comment by lapineige** [comment]
We should mind that : If this PR is accepted, we should probably leave a note somewhere to remove the patch when newer versions of blurhash and ox come out.

**Comment by lapineige** [comment]
Installation works again 🎉

**Comment by lapineige** [comment]
@Tagadda can you merge to testing and then we can work on the recent (auto) upgrades ? :)

**Comment by lapineige** [comment]
CI is happy ;)

**Review by yalh76 — APPROVED** [review]

**Comment by lapineige** [comment]
Let's merge ? :)
The app is broken right now, so it's not high risk 😄

**Comment by lapineige** [comment]
:up: ? :)
I don't want to push you but it's been 3 weeks on that PR and the app install is completely broken right now, and it's a reliable patch as it comes from testing on Mastodon app, so I would consider merging it a safe way to restore a working app :)

**Comment by lapineige** [comment]
Great thanks 🎉

**Pull request merged**
