### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by lapineige**
#112 upgrade to latest version (Mastodon 4.1 level)

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
Before merging, we should borrow improvements from Mastodon Readme : https://github.com/YunoHost-Apps/mastodon_ynh/pull/378#discussion_r1165624762

Users upgrading from an old version, equivalent to Mastodon 3.5 or older (somewhere in spring 2022) : please check it out, you might need to upgrade in 2 steps, using the latest stable version (v2023.11.15) commit.
Proceed with caution (backups) !

**Comment by lapineige** [comment]
Waiting for some testing before merging.

**Comment by lapineige** [comment]
This probably contains the same security patches as https://github.com/YunoHost-Apps/mastodon_ynh/pull/378 does.

We need testers quickly to merge as soon as possible.

**Comment by lapineige** [comment]
CI result here : https://github.com/YunoHost-Apps/glitchsoc_ynh/pull/116#issuecomment-1518959990

**Comment by lapineige** [comment]
Same : https://github.com/YunoHost-Apps/glitchsoc_ynh/pull/117

**Comment by lapineige** [comment]
Needs testers before merging !

**Comment by Tagadda** [comment]
Can't test the upgrade process soon, but it looks good to me.

**Comment by lapineige** [comment]
Yeah it should be fine, but we need real life testing. Anyone ? (please make a backup before)

**Comment by Tagadda** [comment]
!testme

**Comment by lapineige** [comment]
CI is buggy.
It should be exactly the same as in https://github.com/YunoHost-Apps/glitchsoc_ynh/pull/118, so no need to run it again ?

**Review by Tagadda — APPROVED** [review]

**Comment by lapineige** [comment]
I will try a fresh install in the coming days. But if someone can test to upgrade, it would be a lot more valuable.

**Comment by lapineige** [comment]
I will try a fresh install in the coming days. But if someone can test to upgrade, it would be a lot more valuable.

**Comment by lapineige** [comment]
I'm still not able to do it.
I wonder if we should merge anyway…

Please if someone can test this ! :pray:

**Comment by Tagadda** [comment]
Let's merge!!

**Comment by lapineige** [comment]
Did you test it ?
Let's hope it will run smoothly 😅

**Pull request merged**
