### PR TITLE
Upgrade dependencies and include critical security update

### PR DESCRIPTION
**Pull request by AlisonSelby**
## Problem

- Current build of glitchsoc doesn't work because dependencies have been upgraded (Node, Ruby, Yarn). Also includes a critical security update (https://github.com/glitch-soc/mastodon/commit/486e4bc7d3d3dd0c61de2eb316db841a222e36bf).

## Solution

- Bump the versions up, insert corepack commands for installing Yarn, add a condition to only run assets:clean if assets exist. Tested locally and install/backup/restore passed. Upgrade has not passed locally but I ran the test before inserting the assets condition. I'm hoping this can be a jumping point for others to fix glitchsoc-ynh.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by AlisonSelby** [comment]
I have successfully upgraded my live production instance with this branch!

**Comment by alexAubin** [comment]
!testme

**Comment by OniriCorpe** [comment]
great, ci passed!

**Comment by lapineige** [comment]
Awesome work !

**Comment by Tagadda** [comment]
Thank you @AlisonSelby :sparkles:

**Pull request merged**
