### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Tagadda**
## Problem
- Install fails

## Solution
- Port upstream fix
- Update Glitch-Soc version

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
image
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by Tagadda** [comment]
!testme

**Comment by Tagadda** [comment]
Test with `package_check`
image

**Comment by lapineige** [comment]
!testme

**Comment by Tagadda** [comment]
It fails on the dev CI and passes on my local package-check
I don't know why

**Comment by lapineige** [comment]
Oh yeah I see, I first thought it was the version naming issue.
 
I have no clue…
I can't really try to install it for now, sorry.

**Comment by Tagadda** [comment]
Test fails on CI because it cannot write somehow ? I suspect this is due to the CI.
```
282230 WARNING error Could not write file "/var/www/glitchsoc__2/live/yarn-error.log": "UNKNOWN: unknown error, write"
282231 WARNING error An unexpected error occurred: "Unknown system error -122: Unknown system error -122, copyfile '/var/www/glitchsoc__2/.cache/yarn/v6/npm-es-abstract-1.17.7-a4de61b2f66989fc7421676c1cb9787573ace54c-integrity/node_modules/es-abstract/2017/IteratorNext.js' -> '/var/www/glitchsoc__2/live/node_modules/object.getownpropertydescriptors/node_modules/es-abstract/2017/IteratorNext.js'".
282842 ERROR Unable to install glitchsoc: An error occurred inside the app installation script
```

Test succeed on `package_check` and I tested it manually.

**Review by lapineige — APPROVED** [review]

**Pull request merged**
